from django.conf.urls import url
from transportation import views

urlpatterns = [
    url(r'^routes/$',
        views.RouteList.as_view(),
        name=views.RouteList.name),
    url(r'^routes/(?P<pk>[0-9]+)/$',
        views.RouteDetail.as_view(),
        name=views.RouteDetail.name),
    url(r'^rides/$',
        views.RideList.as_view(),
        name=views.RideList.name),
    url(r'^rides/(?P<pk>[0-9]+)/$',
        views.RideDetail.as_view(),
        name=views.RideDetail.name),
    url(r'^drivers/$',
        views.DriverList.as_view(),
        name=views.DriverList.name),
    url(r'^drivers/(?P<pk>[0-9]+)/$',
        views.DriverDetail.as_view(),
        name=views.DriverDetail.name),
    url(r'^vehicles/$',
        views.VehicleList.as_view(),
        name=views.VehicleList.name),
    url(r'^vehicles/(?P<pk>[0-9]+)/$',
        views.VehicleDetail.as_view(),
        name=views.VehicleDetail.name),
    url(r'^clients/$',
        views.ClientList.as_view(),
        name=views.ClientList.name),
    url(r'^clients/(?P<pk>[0-9]+)/$',
        views.ClientDetail.as_view(),
        name=views.ClientDetail.name),
    url(r'^client-orders/$',
        views.ClientOrderList.as_view(),
        name=views.ClientOrderList.name),
    url(r'^client-orders/(?P<pk>[0-9]+)/$',
        views.ClientOrderDetail.as_view(),
        name=views.ClientOrderDetail.name),
    url(r'^$',
        views.ApiRoot.as_view(),
        name=views.ApiRoot.name),
]
