# Generated by Django 2.2.1 on 2019-05-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=13, unique=True)),
                ('status', models.CharField(default='normal', max_length=15)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=15)),
                ('end', models.CharField(default='', max_length=15)),
                ('date_and_time', models.DateTimeField()),
            ],
            options={
                'ordering': ('date_and_time',),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=15)),
                ('end', models.CharField(default='', max_length=15)),
                ('distance', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_license', models.CharField(default='', max_length=7)),
                ('car_model', models.CharField(default='', max_length=15)),
                ('color', models.CharField(default='white', max_length=15)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='transportation.Ride')),
            ],
            options={
                'ordering': ('car_license',),
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='transportation.Route'),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=13, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='transportation.Ride')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ClientRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='transportation.Client')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.Ride')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='transportation.Ride'),
        ),
    ]
